routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->name('welcome');

Auth::routes(['verify' => true]);

Route::group(['prefix' => 'user', 'middleware' => 'auth'], function () {
    Route::get('home', 'HomeController@userHome')->name('user_home');

    Route::group(['prefix'  => 'rent'], function () {
        Route::get('/{id}', 'PeminjamanUserController@create_rent')->name('rentUser.create');
        Route::get('/', 'PeminjamanUserController@index')->name('rentUser.index');
        Route::get('/detail/{id}', 'PeminjamanUserController@show')->name('rentUser.show');
        Route::get('/{id}/bayar', 'PeminjamanUserController@bayar')->name('rentUser.bayar');
        Route::post('/', 'PeminjamanUserController@store_rent')->name('rentUser.store');
        Route::post('/{id}/bayar', 'PeminjamanUserController@konfirmasi')->name('rentUser.konfirmasi');
    });

    Route::resource('CustomerUser', 'CustomerUserController');
});

Route::group(['prefix' => 'admin', 'middleware' => 'is_admin'], function () {

    Route::get('dashboard', 'DashboardController@index')->name('adminDashboard');

    Route::get('rent/create', 'RentController@create_rent_admin')->name('create_rent_admin');
    Route::post('rent/create', 'RentController@store_rent_admin')->name('store_rent_admin');

    // Pending rent
    Route::get('rent/pending', 'RentController@index')->name('pending_index');
    Route::get('rent/pending/{id}', 'RentController@pending_show')->name('pending_show');
    Route::post('rent/pending', 'RentController@pending_update')->name('pending_update');
    Route::delete('rent/pending/{id}', 'RentController@pending_destroy')->name('pending_destroy');

    // on rent
    Route::get('rent/jalan', 'RentController@index')->name('rent_index');
    Route::get('rent/jalan/{id}', 'RentController@rent_show')->name('rent_show');
    Route::post('rent/jalan/{id}', 'RentController@rent_update')->name('rent_update');

    // Returned rent
    Route::get('rent/kembali', 'RentController@index')->name('return_index');
    Route::get('rent/kembali/{id}', 'RentController@rent_show')->name('return_info');

    // Checkout rent
    Route::get("rent/checkout/{id}", "RentController@checkout")->name("checkout_rent");

    // Car route
    Route::resource('car', 'CarController');

    // Driver route
    Route::resource('driver', 'DriverController');

    // Payment route
    Route::resource('payment', 'PaymentController');

    // Armada route
    Route::resource('armada', 'ArmadaController');

    // Customer route
    Route::resource('customer', 'CustomerController');

    // Read notifications
    Route::post('read/{id}', 'ReadNotificationController')->name('readNotification');
});

app/Payment.php
<?php

namespace App;

use App\Rent;
use App\User;
use Illuminate\Database\Eloquent\Model;

class Payment extends Model
{
    public $fillable = [
        'nomor_tagihan'
    ];

    public function rents() {
        return $this->hasOne('App\Rent', 'id', 'id_peminjaman');
    }

    public function customers() {
        return $this->hasOne('App\Customer', 'id', 'id_customer');
    }

    public function getFormatTotalHargaAttribute() {
        return "Rp.{$this->total_harga},-";
    }

}

app/Rent.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Carbon\Carbon;

class Rent extends Model
{
    
    protected $fillable = [
        'id_customer', 'id_mobil', 'id_armada', 'tipe_peminjaman', 'id_driver', 'mulai_sewa', 'lama_sewa', 'habis_sewa', 'lokasi_penjemputan'
    ];
    
    /**
     * 
     * RELATIONSHIP
     *
     */
    public function customers() {
        return $this->hasOne('App\Customer', 'id', 'id_customer');
    }

    public function cars() {
        return $this->hasOne('App\Car', 'id', 'id_mobil');
    }

    public function drivers() {
        return $this->hasOne('App\Driver', 'id', 'id_driver');
    }

    public function armadas() {
        return $this->hasOne('App\Armada', 'id', 'id_armada');
    }

    
    /**
     * 
     * MUTATOR
     *
     */
    public function getFormatMulaiSewaAttribute() {
        return Carbon::parse($this->mulai_sewa)->format('j F Y');
    }

    public function getFormatLamaSewaAttribute() {
        return $this->lama_sewa." Hari";
    }

    public function getFormatHabisSewaAttribute() {
        return Carbon::parse($this->habis_sewa)->format('j F Y');
    }

    public function getFormatTipePeminjamanAttribute() {
        $text = ($this->tipe_peminjaman == 3 ? 'Mobil, Sopir dan Bahan bakar' : ($this->tipe_peminjaman == 2 ? 'Mobil dan Sopir' : 'Hanya mobil'));

        return $text;
    }

    public function getNamaLengkapMobilAttribute() {
        return "{$this->cars->merk_mobil} {$this->cars->nama_mobil}";
    }

    public function getLokasiGambarMobilAttribute() {
        return "images/{$this->cars->gambar}";
    }

    public function getLokasiGambarUserAttribute() {
        return "images/{$this->users->profile}";
    }

    public function getHargaMobilAttribute() {
        return $this->cars->harga * $this->lama_sewa;
    }

    public function getFormatHargaMobilAttribute() {
        return "Rp.".$this->harga_mobil.",-";
    }

    public function getHargaDriverAttribute() {
        if ($this->tipe_peminjaman == 2 || $this->tipe_peminjaman == 3) {
            $harga_driver = $this->lama_sewa * 100000;
            return $harga_driver;
        }

        return 0;
    }

    public function getFormatHargaDriverAttribute() {
        if ($this->harga_driver != 0) {
            return "Rp.{$this->harga_driver},-";
        }

        return "-";
    }

    public function getHargaBahanBakarAttribute() {
        if ($this->tipe_peminjaman == 3) {
            $harga_bahan_bakar = $this->lama_sewa * 100000;
            return $harga_bahan_bakar;
        }

        return 0;
    }

    public function getFormatHargaBahanBakarAttribute() {
        if ($this->harga_bahan_bakar != 0) {
            return "Rp.{$this->harga_bahan_bakar},-";
        }

        return "-";
    }

    public function getTotalHargaAttribute() {
        $harga = $this->harga_mobil + $this->harga_driver + $this->harga_bahan_bakar;
        return $harga;
    }

    public function getFormatTotalHargaAttribute() {
        return "Rp.".$this->total_harga.",-";
    }
}

app/Http/Controllers/PaymentController.php
<?php

namespace App\Http\Controllers;

use App\Payment;
use App\Rent;
use App\Armada;
use App\Driver;
use Alert;
use Illuminate\Http\Request;

class PaymentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        // set default order value
        $orderBy = $request->orderBy ? $request->orderBy : 'created_at';
        $orderType = $request->orderType ? $request->orderType : 'DESC';

        if ($request->has('search_query')) {
            $payments = Payment::with('customers')
            ->join('customers', 'payments.id_customer', '=', 'customers.id')
            ->select('payments.*', 'customers.nama')
            ->where('nama', 'LIKE', '%'.$request->search_query.'%')
            ->orWhere('nomor_tagihan', 'LIKE', '%'.$request->search_query.'%')
            ->orWhere('total_harga', 'LIKE', '%'.$request->search_query.'%')
            ->orWhere('status', 'LIKE', '%'.$request->search_query.'%')
            ->orderBy($orderBy, $orderType)
            ->paginate(10);
        } else {
            $payments = Payment::with('customers')
            ->join('customers', 'payments.id_customer', '=', 'customers.id')
            ->select('payments.*', 'customers.nama')
            ->orderBy($orderBy, $orderType)
            ->paginate(10);
        }

        // append order query
        if ($orderBy != 'created_at') {
            $payments->appends([
                'orderBy'   => $orderBy,
                'orderType' => $orderType
            ]);
        }

        return view('payment.index')->with([
            'payments' => $payments,
            'orderType' => $orderType == 'DESC' ? 'ASC' : 'DESC'
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Payment  $payment
     * @return \Illuminate\Http\Response
     */
    public function show(Payment $payment)
    {
        $payment = Payment::with("rents", "customers")
        ->where("id", $payment->id)
        ->first();

        return view("payment.show")->with("payment", $payment);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Payment  $payment
     * @return \Illuminate\Http\Response
     */
    public function edit(Payment $payment)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Payment  $payment
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Payment $payment)
    {
        $payment = Payment::find($payment->id);
        $payment->status = 'lunas';
        $payment->save();

        Alert::success('Berhasil', 'Pembayaran telah dikonfirmasi');
        return redirect()->route('pending_show', $payment->rents->id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Payment  $payment
     * @return \Illuminate\Http\Response
     */
    public function destroy(Payment $payment)
    {

    }
}

resources/views/payment/index.blade.php
@extends('adminlte::page')

@section('content')
<div class="card">
    <div class="card-header d-flex flex-wrap border-bottom-0">
        <h4 class="card-title text-bold align-self-center">
            Daftar tagihan
        </h4> 
        <form method="GET" action="{{ route('payment.index') }}" class="input-group ml-auto" style="width: 250px">
            <input type="text" class="form-control bg-light" name="search_query" placeholder="search" required>
            <div class="input-group-append">
                <button class="btn btn-light btn-sm px-3 border"><span class="fa fa-search"></span></button>
            </div>
        </form>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-vertical-center">
                <thead>
                    <tr>
                        <th>
                            NO
                        </th>
                        <th>
                            NOMOR TAGIHAN
                        </th>
                        <th>
                            <a href="{{ Request::fullUrlWithQuery([
                                'orderBy'   => 'nama',
                                'orderType' => $orderType
                            ]) }}" class="btn btn-link text-dark font-weight-bold p-0">
                                NAMA PELANGGAN
                                <i class="fas fa-sort"></i>
                            </a>
                        </th>
                        <th>
                            <a href="{{ Request::fullUrlWithQuery([
                                'orderBy'   => 'total_harga',
                                'orderType' => $orderType
                            ]) }}" class="btn btn-link text-dark font-weight-bold p-0">
                                TOTAL TAGIHAN
                                <i class="fas fa-sort"></i>
                            </a>
                        </th>
                        <th>
                            <a href="{{ Request::fullUrlWithQuery([
                                'orderBy'   => 'status',
                                'orderType' => $orderType
                            ]) }}" class="btn btn-link text-dark font-weight-bold p-0">
                                STATUS
                                <i class="fas fa-sort"></i>
                            </a>
                        </th>
                        <th class="text-right">Aksi</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($payments as $key => $payment)
                    <tr>
                        <td>
                            {{ $key + 1 }}
                        </td>
                        <td>
                            {{ $payment->nomor_tagihan }}
                        </td>
                        <td>
                            <a href="{{ route("customer.show", $payment->customers->id) }}">
                                {{ $payment->customers->nama }}
                            </a>
                        </td>
                        <td>
                            {{ $payment->format_total_harga }}
                        </td>
                        <td>
                            @if ($payment->status == 'utang')
                            <div class="text-danger">
                                <i class="fa fa-hourglass-half" aria-hidden="true"></i> Belum dibayar
                            </div>
                            @else
                            <div class="text-success">
                                <i class="fas fa-check    "></i> {{ $payment->status}}
                            </div>
                            @endif
                        </td>
                        <td class="text-right">
                            <a href="{{ route("payment.show", $payment->id) }}" class="btn btn-success btn-sm" >
                                <i class="fas fa-eye    "></i>
                            </a>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
        {{ $payments->links() }}
    </div>
</div>
@endsection

resources/views/payment/show.blade.php
@extends('adminlte::page')

@section('content')
<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-header d-flex border-0">
                <h4 class="card-title my-auto mr-auto">
                    <a href="{{ route('payment.index') }}" class="mr-3">
                        <span class="fa fa-arrow-left text-primary"></span>
                    </a>
                    Detail tagihan
                </h4>
                </h4>
                @if ($payment->rents->status == 'pending')
                <form class="d-inline" action="{{ route('payment.update', $payment->id) }}" method="post">
                    @csrf
                    @method('PUT')
                    <button type="submit" class="btn btn-primary">
                        <i class="fas fa-check    "></i> Konfirmasi
                    </button>
                </form>
                @endif
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered">
                        <tr>
                            <th>Jasa</th>
                            <th>Biaya</th>
                            <th>Waktu</th>
                            <th class="text-right">Total</th>
                        </tr>
                        <tr>
                            <td class="w-50">Mobil</td>
                            <td>
                                {{ $payment->rents->format_harga_mobil }}
                            </td>
                            <td>
                                {{ $payment->rents->format_lama_sewa }}
                            </td>
                            <th class="text-right">
                                {{ $payment->rents->format_harga_mobil }}
                            </th>
                        </tr>
                        @if ($payment->rents->tipe_peminjaman != 1)
                        <tr>
                            <td class="w-50">Sopir</td>
                            <td>
                                Rp.100000,-
                            </td>
                            <td>
                                {{ $payment->rents->format_lama_sewa }}
                            </td>
                            <th class="text-right">{{ $payment->rents->format_harga_driver }}</th>
                        <tr>
                        @endif
                        @if ($payment->rents->tipe_peminjaman == 3)
                        <tr>
                            <td class="w-50">Bahan bakar</td>
                            <td>
                                Rp.100000,-
                            </td>
                            <td>
                                {{ $payment->rents->format_lama_sewa }}
                            </td>
                            <th class="text-right">
                                {{ $payment->rents->format_harga_bahan_bakar }}
                            </th>
                        </tr>
                        @endif
                        <tr>
                            <td colspan="3">
                                Total akhir
                            </td>
                            <th class="text-right border-top">
                                {{ $payment->rents->format_total_harga }}
                            </th>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <div class="col-lg-12">
        <div class="card">
            <div class="card-header border-0">
                <div class="card-title">
                    Bukti pembayaran
                </div>
            </div>
            <div class="card-body text-center">
                <img src="{{ asset('storage/bukti/'.$payment->bukti_pembayaran) }}" class="img-fluid text-danger" alt="Pelanggan belum mengupload bukti pembayaran">
            </div>
        </div>
    </div>
</div>
@endsection