routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->name('welcome');

Auth::routes(['verify' => true]);

Route::group(['prefix' => 'user', 'middleware' => 'auth'], function () {
    Route::get('home', 'HomeController@userHome')->name('user_home');

    Route::group(['prefix'  => 'rent'], function () {
        Route::get('/{id}', 'PeminjamanUserController@create_rent')->name('rentUser.create');
        Route::get('/', 'PeminjamanUserController@index')->name('rentUser.index');
        Route::get('/detail/{id}', 'PeminjamanUserController@show')->name('rentUser.show');
        Route::get('/{id}/bayar', 'PeminjamanUserController@bayar')->name('rentUser.bayar');
        Route::post('/', 'PeminjamanUserController@store_rent')->name('rentUser.store');
        Route::post('/{id}/bayar', 'PeminjamanUserController@konfirmasi')->name('rentUser.konfirmasi');
    });

    Route::resource('CustomerUser', 'CustomerUserController');
});

Route::group(['prefix' => 'admin', 'middleware' => 'is_admin'], function () {

    Route::get('dashboard', 'DashboardController@index')->name('adminDashboard');

    Route::get('rent/create', 'RentController@create_rent_admin')->name('create_rent_admin');
    Route::post('rent/create', 'RentController@store_rent_admin')->name('store_rent_admin');

    // Pending rent
    Route::get('rent/pending', 'RentController@index')->name('pending_index');
    Route::get('rent/pending/{id}', 'RentController@pending_show')->name('pending_show');
    Route::post('rent/pending', 'RentController@pending_update')->name('pending_update');
    Route::delete('rent/pending/{id}', 'RentController@pending_destroy')->name('pending_destroy');

    // on rent
    Route::get('rent/jalan', 'RentController@index')->name('rent_index');
    Route::get('rent/jalan/{id}', 'RentController@rent_show')->name('rent_show');
    Route::post('rent/jalan/{id}', 'RentController@rent_update')->name('rent_update');

    // Returned rent
    Route::get('rent/kembali', 'RentController@index')->name('return_index');
    Route::get('rent/kembali/{id}', 'RentController@rent_show')->name('return_info');

    // Checkout rent
    Route::get("rent/checkout/{id}", "RentController@checkout")->name("checkout_rent");

    // Car route
    Route::resource('car', 'CarController');

    // Driver route
    Route::resource('driver', 'DriverController');

    // Payment route
    Route::resource('payment', 'PaymentController');

    // Armada route
    Route::resource('armada', 'ArmadaController');

    // Customer route
    Route::resource('customer', 'CustomerController');

    // Read notifications
    Route::post('read/{id}', 'ReadNotificationController')->name('readNotification');
});

app/Rent.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Carbon\Carbon;

class Rent extends Model
{
    
    protected $fillable = [
        'id_customer', 'id_mobil', 'id_armada', 'tipe_peminjaman', 'id_driver', 'mulai_sewa', 'lama_sewa', 'habis_sewa', 'lokasi_penjemputan'
    ];
    
    /**
     * 
     * RELATIONSHIP
     *
     */
    public function customers() {
        return $this->hasOne('App\Customer', 'id', 'id_customer');
    }

    public function cars() {
        return $this->hasOne('App\Car', 'id', 'id_mobil');
    }

    public function drivers() {
        return $this->hasOne('App\Driver', 'id', 'id_driver');
    }

    public function armadas() {
        return $this->hasOne('App\Armada', 'id', 'id_armada');
    }

    
    /**
     * 
     * MUTATOR
     *
     */
    public function getFormatMulaiSewaAttribute() {
        return Carbon::parse($this->mulai_sewa)->format('j F Y');
    }

    public function getFormatLamaSewaAttribute() {
        return $this->lama_sewa." Hari";
    }

    public function getFormatHabisSewaAttribute() {
        return Carbon::parse($this->habis_sewa)->format('j F Y');
    }

    public function getFormatTipePeminjamanAttribute() {
        $text = ($this->tipe_peminjaman == 3 ? 'Mobil, Sopir dan Bahan bakar' : ($this->tipe_peminjaman == 2 ? 'Mobil dan Sopir' : 'Hanya mobil'));

        return $text;
    }

    public function getNamaLengkapMobilAttribute() {
        return "{$this->cars->merk_mobil} {$this->cars->nama_mobil}";
    }

    public function getLokasiGambarMobilAttribute() {
        return "images/{$this->cars->gambar}";
    }

    public function getLokasiGambarUserAttribute() {
        return "images/{$this->users->profile}";
    }

    public function getHargaMobilAttribute() {
        return $this->cars->harga * $this->lama_sewa;
    }

    public function getFormatHargaMobilAttribute() {
        return "Rp.".$this->harga_mobil.",-";
    }

    public function getHargaDriverAttribute() {
        if ($this->tipe_peminjaman == 2 || $this->tipe_peminjaman == 3) {
            $harga_driver = $this->lama_sewa * 100000;
            return $harga_driver;
        }

        return 0;
    }

    public function getFormatHargaDriverAttribute() {
        if ($this->harga_driver != 0) {
            return "Rp.{$this->harga_driver},-";
        }

        return "-";
    }

    public function getHargaBahanBakarAttribute() {
        if ($this->tipe_peminjaman == 3) {
            $harga_bahan_bakar = $this->lama_sewa * 100000;
            return $harga_bahan_bakar;
        }

        return 0;
    }

    public function getFormatHargaBahanBakarAttribute() {
        if ($this->harga_bahan_bakar != 0) {
            return "Rp.{$this->harga_bahan_bakar},-";
        }

        return "-";
    }

    public function getTotalHargaAttribute() {
        $harga = $this->harga_mobil + $this->harga_driver + $this->harga_bahan_bakar;
        return $harga;
    }

    public function getFormatTotalHargaAttribute() {
        return "Rp.".$this->total_harga.",-";
    }
}

app/Http/Controllers/RentController.php
<?php

namespace App\Http\Controllers;

use Alert;
use App\Rent;
use App\Car;
use App\Driver;
use App\Armada;
use App\Customer;
use App\Payment;
use Carbon\Carbon;
use Illuminate\Http\Request;

class RentController extends Controller
{
    /**
     * 
     * MENAMPILKAN DATA PENYEWAAN MOBIL
     *
     */
    public function index(Request $request)
    {

        // set default order value
        $orderBy = $request->orderBy ? $request->orderBy : 'updated_at';
        $orderType = $request->orderType ? $request->orderType : 'DESC';

        $status = request()->segment(count(request()->segments()));

        if ($request->has('search_query')) {
            $rents = Rent::join('customers', 'rents.id_customer', '=', 'customers.id')
            ->join('cars', 'rents.id_mobil', '=', 'cars.id')
            ->select('rents.*', 'customers.nama', \DB::raw('CONCAT(merk_mobil," ",nama_mobil) as nama_mobil'))
            ->where('status', $status)
            ->where(function($q) use ($request) {
                $q->where('nama', 'LIKE', '%'.$request->search_query.'%');
                $q->orWhere(\DB::raw('CONCAT(merk_mobil," ",nama_mobil)'), 'LIKE', '%'.$request->search_query.'%');
            })
            ->orderBy($orderBy, $orderType)
            ->paginate(10);
        } else {
            $rents = Rent::join('customers', 'rents.id_customer', '=', 'customers.id')
            ->join('cars', 'rents.id_mobil', '=', 'cars.id')
            ->select('rents.*', 'customers.nama', \DB::raw('CONCAT(merk_mobil," ",nama_mobil) as nama_mobil'))
            ->where('status', $status)
            ->orderBy($orderBy, $orderType)
            ->paginate(10);
        }

        // append order query
        if ($orderBy != 'updated_at') {
            $rents->appends([
                'orderBy'   => $orderBy,
                'orderType' => $orderType
            ]);
        }

        return view('rent.index')->with([
            'rents'     => $rents,
            'orderType' => $orderType == 'DESC' ? 'ASC' : 'DESC'
        ]);
    }

    /**
     * 
     * FORM PEMBUATAN PENYEWAAN BARU DARI ROLE ADMIN
     *
     */
    public function create_rent_admin() {
        $customers = Customer::all();
        $cars = Car::all();

        return view('rent.create')->with([
            'customers'     => $customers,
            'cars'      => $cars,
        ]);
    }
    
    /**
     * 
     * MEMBUAT PENYEWAAN DARI ROLE ADMIN
     *
     */
    public function store_rent_admin(Request $request) {
        $cars = Car::where('id', $request->id_mobil)->first();
        $tipe_harga = ($request->tipe_peminjaman == 3 ? 200000 : ($request->tipe_peminjaman == 2 ? 100000 : 0));
        $harga = (intval($cars->harga) + $tipe_harga) * intval($request->lama_sewa);
        $habis_sewa = Carbon::parse($request->mulai_sewa)->addDay($request->lama_sewa);

        if ($request->create == "1") {
            $rent = new Rent;
            $rent->id_customer = $request->id_customer;
            $rent->id_mobil = $request->id_mobil;
            $rent->tipe_peminjaman = $request->tipe_peminjaman;
            $rent->mulai_sewa = $request->mulai_sewa;
            $rent->lama_sewa = $request->lama_sewa;
            $rent->habis_sewa = $habis_sewa;
            $rent->lokasi_penjemputan = $request->lokasi_penjemputan;
            $rent->status = 'pending';
            $rent->save();

            Alert::success('Berhasil', 'Pesanan telah dibuat');
            return redirect()->route('pending_index');
        }

        // cek harga dengan mengembalikan nilai harga
        return back()->withInput()->with('harga', $harga);
    }
    
    /**
     * 
     * MENGEMBALIKAN MOBIL
     * 
     */
    public function rent_update(Request $request) {
        $rent = Rent::find($request->id);
        $rent->status = 'kembali';
        $rent->save();

        Alert::success('Berhasil', 'Mobil telah dikembalikan!');
        return redirect()->route('return_index');
    }

    /**
     * 
     * MENAMPILKAN DATA LENGKAP TENTANG MOBIL DALAM PEMINJAMAN
     *
     */
    public function rent_show($id)
    {
        $rent = Rent::with('customers', 'cars', 'drivers', 'armadas')
        ->find($id);

        return view('rent.show')->with('rent', $rent);
    }

    /**
     * 
     * MENGHAPUS DATA PEMINJAMAN
     *
     */
    public function pending_destroy($id)
    {
        Rent::find($id)->delete();

        Alert::success('Berhasil', 'Data telah dihapus');
        return redirect()->back();
    }
    
    /**
     * 
     * MENAMPILKAN INFORMASI DETAIL SEWA YANG BELUM DIKONFIRMASI
     *
     */
    public function pending_show(Request $request) {
        $drivers    = Driver::where('driver_status', 'tersedia')->get();
        $rent       = Rent::where('id', $request->id)->first();
        $armadas    = Armada::where(['status' => 'tersedia', 'id_mobil' => $rent->id_mobil])->get();

        return view("rent.confirm")->with([
            'drivers'   => $drivers,
            'armadas'   => $armadas,
            'rent'      => $rent
        ]);
    }
    
    /**
     * 
     * MENGKONFIRMASI PENYEWAAN
     *
     */
    public function pending_update(Request $request) {

        // Menambahkan driver & armada
        $rent = Rent::find($request->id);
        $rent->id_driver = $request->id_driver;
        $rent->id_armada = $request->id_armada;
        $rent->status = 'jalan';
        $rent->save();

        // Update armada mobil status
        $armada = Armada::find($request->id_armada);
        $armada->status = 'jalan';
        $armada->save();

        // Update driver status
        if ($request->has("id_driver")) {
            $driver = Driver::find($request->id_driver);
            $driver->driver_status = 'jalan';
            $driver->save();
        }

        Alert::success('Berhasil', 'Pesanan telah dikonfirmasi');
        return redirect()->route("rent_index");
    }

}

resources/views/rent/confirm.blade.php
@extends('adminlte::page')

@section('content')
<div class="row">
    <div class="col-md-6">
        <div class="card">
            <div class="card-header border-0">
                <div class="card-title">
                    <a href="{{ url()->previous() }}" class="mr-3">
                        <span class="fa fa-arrow-left text-primary"></span>
                    </a>
                    Informasi lengkap sewa
                </div>
            </div>
            <div class="card-body">
                <table class="table table-borderless">
                    <tbody>
                        <tr>
                            <td class="text-muted w-50">Nama pelanggan</td>
                            <th class="text-right">{{ $rent->customers->nama }}</th>
                        </tr>
                        <tr>
                            <td class="text-muted w-50">Nama mobil</td>
                            <th class="text-right">{{ $rent->nama_lengkap_mobil }}</th>
                        </tr>
                        <tr>
                            <td class="text-muted">Mulai sewa</td>
                            <th class="text-right">{{ $rent->format_mulai_sewa }}</th>
                        </tr>
                        <tr>
                            <td class="text-muted">Lama sewa</td>
                            <th class="text-right">{{ $rent->format_lama_sewa }}</th>
                        </tr>
                        <tr>
                            <td class="text-muted">Habis sewa</td>
                            <th class="text-right">{{ $rent->format_habis_sewa }}</th>
                        </tr>
                        <tr>
                            <td class="text-muted">Tipe peminjaman</td>
                            <th class="text-right">{{ $rent->format_tipe_peminjaman }}</th>
                        </tr>
                        @if (!empty($rent->lokasi_penjemputan))
                        <tr>
                            <td class="text-muted">Lokasi penjemputan</td>
                            <th class="text-right">{{ $rent->lokasi_penjemputan }}</th>
                        </tr>
                        @endif
                        <tr>
                            <td class="text-muted">Status</td>
                            <th class="text-right">
                                {{ $rent->status }}
                            </th>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div class="col-lg-6">
        <div class="card">
            <div class="card-header border-0">
                <div class="card-title">
                    Konfirmasi pesanan
                </div>
            </div>
            <div class="card-body">
                <form action="{{ route("pending_update") }}" method="post">
                    <input class="d-none" type="text" name="id" value="{{ $rent->id }}">
                    <div class="form-group">
                        <label for="mobil">Mobil</label>
                        <input type="text" id="mobil" class="form-control" value="{{ $rent->nama_lengkap_mobil }}" aria-describedby="mobil_help" disabled >
                        <small id="mobil_help" class="text-muted"></small>
                    </div>
                    <div class="form-group">
                        <label for="id_armada">Pilih armada</label>
                        <select class="form-control" name="id_armada" id="id_armada">
                            <option disabled selected></option>
                            @foreach ($armadas as $armada)
                                <option value="{{ $armada->id }}">
                                    {{ $armada->nomor_plat }}
                                </option> 
                            @endforeach
                        </select>
                        @forelse ($armadas as $item)
                        @empty
                        <p class="form-text text-muted">
                            Silakan tambah armada terlebih dahulu
                        </p>
                        @endforelse
                    </div>
                    @if ($rent->tipe_peminjaman != 1)
                    <div class="form-group">
                        <label for="id_driver">Pilih driver</label>
                        <select class="form-control" name="id_driver" id="id_driver">
                            <option disabled selected></option>
                            @foreach ($drivers as $driver)
                            <option value="{{ $driver->id }}">
                                {{ $driver->driver_name }}
                            </option>
                            @endforeach
                        </select>
                        </div>
                        @forelse ($drivers as $item)
                        @empty
                        <p class="form-text text-muted">
                            Semua driver sedang sibuk, silakan tambah driver terlebih dahulu
                        </p>
                        @endforelse
                    @endif
                    <button type="submit" class="btn btn-primary">Konfirmasi</button>
                </form>
            </div>
        </div>
    </div>
</div> 
@endsection

resources/views/rent/index.blade.php
@extends('adminlte::page')

@section('content')
<div class="row">
    <div class="col">
        <div class="card">
            <div class="card-header d-flex flex-wrap border-bottom-0">
                <h4 class="card-title text-bold align-self-end mb-2">Daftar penyewaan</h4> 
                <form method="GET" action="{{ url()->current() }}" class="input-group ml-auto mr-2" style="width: 250px">
                    <input type="text" class="form-control bg-light" name="search_query" placeholder="search" required>
                    <div class="input-group-append">
                        <button class="btn btn-light btn-sm px-3 border"><span class="fa fa-search"></span></button>
                    </div>
                </form>
                <a class="btn btn-primary" href="{{ route('create_rent_admin') }}" role="button">
                    <i class="fas fa-plus"></i>
                </a>
            </div>
            <div class="card-body">
                <div class="table-responsive mb-4">
                    <table class="table table-vertical-center">
                        <thead>
                            <tr>
                                <th>
                                    NO
                                </th>
                                <th>
                                    <a href="{{ Request::fullUrlWithQuery([
                                        'orderBy'   => 'nama',
                                        'orderType' => $orderType
                                    ]) }}" class="btn btn-link text-dark font-weight-bold p-0">
                                        NAMA PELANGGAN
                                        <i class="fas fa-sort"></i>
                                    </a>
                                </th>
                                <th>
                                    <a href="{{ Request::fullUrlWithQuery([
                                        'orderBy'   => 'nama_mobil',
                                        'orderType' => $orderType
                                    ]) }}" class="btn btn-link text-dark font-weight-bold p-0">
                                        NAMA MOBIL
                                        <i class="fas fa-sort"></i>
                                    </a>
                                </th>
                                <th>
                                    <a href="{{ Request::fullUrlWithQuery([
                                        'orderBy'   => 'mulai_sewa',
                                        'orderType' => $orderType
                                    ]) }}" class="btn btn-link text-dark font-weight-bold p-0">
                                        MULAI SEWA
                                        <i class="fas fa-sort"></i>
                                    </a>
                                </th>
                                <th>
                                    <a href="{{ Request::fullUrlWithQuery([
                                        'orderBy'   => 'lama_sewa',
                                        'orderType' => $orderType
                                    ]) }}" class="btn btn-link text-dark font-weight-bold p-0">
                                        LAMA SEWA
                                        <i class="fas fa-sort"></i>
                                    </a>
                                </th>
                                <th>
                                    <a href="{{ Request::fullUrlWithQuery([
                                        'orderBy'   => 'tipe_peminjaman',
                                        'orderType' => $orderType
                                    ]) }}" class="btn btn-link text-dark font-weight-bold p-0">
                                        TIPE PEMINJAMAN
                                        <i class="fas fa-sort"></i>
                                    </a>
                                </th>
                                <th class="text-right">AKSI</th>
                            </tr>
                        </thead>
                        <tbody>
                            @forelse ($rents as $key => $rent)
                            <tr>
                                <td>
                                    {{ $key + 1 }}
                                </td>
                                <td>
                                    <a href="{{ route("customer.show", $rent->id_customer) }}">
                                        {{ $rent->nama}}
                                    </a>
                                </td>
                                <td>
                                    <a href="{{ route("car.show", $rent->id_mobil) }}">
                                        {{ $rent->nama_lengkap_mobil}}
                                    </a>
                                </td>
                                <td>{{ $rent->format_mulai_sewa }}</td>
                                <td>{{ $rent->lama_sewa.' Hari' }}</td>
                                <td>
                                    {{ $rent->format_tipe_peminjaman }}
                                </td>
                                <td class="text-right">

                                    @if ($rent->status == 'pending')
                                    <a href="{{ route('pending_show', $rent->id) }}" type="button" class="btn btn-primary btn-sm"><span class="fa fa-check"></span></a>
                                    <button type="button" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#modalDelete">
                                        <i class="fas fa-trash    "></i>
                                    </button>


                                    @elseif ($rent->status == 'jalan')
                                    <a href="{{ route('rent_show', $rent->id) }}" type="button" class="btn btn-primary btn-sm">
                                        <i class="fas fa-arrow-right    "></i>
                                    </a>

                                    @else
                                    <a href="{{ route('return_info', $rent->id) }}" type="button" class="btn btn-success btn-sm">
                                        <i class="fas fa-eye    "></i>
                                    </a>
                                    @endif

                                </td>
                            </tr>
                            @include('rent.modalDelete')
                            @empty
                            <tr>
                                <td class="text-center" colspan="6">Data not found</td>
                            </tr>
                            @endforelse
                        </tbody>
                    </table>
                </div>
                {{ $rents->links() }}
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/rent/modalDelete.blade.php
<!-- Modal -->
<div class="modal fade" id="modalDelete" tabindex="-1" role="dialog" aria-labelledby="modalDelete" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header border-0">
                <h5 class="modal-title">Konfirmasi</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
            </div>
            <div class="modal-body">
                Apa anda yakin ingin menghapus data ini?
            </div>
            <div class="modal-footer border-0">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <form action="{{ route("pending_destroy", $rent->id) }}" method="post" class="d-inline">
                    @csrf
                    @method("DELETE")
                    <button type="submit" class="btn btn-primary">
                        Ya, Hapus!
                    </button>
                </form>
            </div>
        </div>
    </div>
</div>

resources/views/rent/return.blade.php
@extends('adminlte::page')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-lg">
                <div class="card">
                    <div class="card-header">
                        <div class="card-title">Rental list</div>
                    </div>
                    <div class="card-body">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>Nama</th>
                                    <th>Mobil</th>
                                    <th>Mulai sewa</th>
                                    <th>Lama sewa</th>
                                    <th>Status</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($rents as $rent)
                                <tr>
                                    <td>{{ $rent->users->name}}</td>
                                    <td>{{ $rent->nama_lengkap_mobil}}</td>
                                    <td>{{ $rent->format_mulai_sewa }}</td>
                                    <td>{{ $rent->lama_sewa.' Hari' }}</td>
                                    <td> {{ $rent->status }} </td>
                                    <td>
                                        <a href="{{ route('rent.show', $rent->id) }}" type="button" class="btn btn-success btn-sm">View</a>
                                        <a href="#" class="btn btn-primary btn-sm">Checkout</a>
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                        {{ $rents->links() }}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/rent/show.blade.php
@extends('adminlte::page')

@section('content')
<div class="row">
    <div class="col-lg-6">
        <div class="card">
            <div class="card-header border-0">
                <div class="card-title">
                    <a href="{{ url()->previous() }}" class="mr-3">
                        <span class="fa fa-arrow-left text-primary"></span>
                    </a>
                    Informasi lengkap sewa
                </div>
            </div>
            <div class="card-body">
                <table class="table table-borderless">
                    <tbody>
                        <tr>
                            <td class="text-muted w-50">Nama pelanggan</td>
                            <th class="text-right">{{ $rent->customers->nama }}</th>
                        </tr>
                        <tr>
                            <td class="text-muted w-50">Nama mobil</td>
                            <th class="text-right">{{ $rent->nama_lengkap_mobil }}</th>
                        </tr>
                        <tr>
                            <td class="text-muted">Nomor plat</td>
                            <th class="text-right">{{ $rent->armadas->nomor_plat }}</th>
                        </tr>
                        <tr>
                            <td class="text-muted">Mulai sewa</td>
                            <th class="text-right">{{ $rent->format_mulai_sewa }}</th>
                        </tr>
                        <tr>
                            <td class="text-muted">Lama sewa</td>
                            <th class="text-right">{{ $rent->format_lama_sewa }}</th>
                        </tr>
                        <tr>
                            <td class="text-muted">Habis sewa</td>
                            <th class="text-right">{{ $rent->format_habis_sewa }}</th>
                        </tr>
                        <tr>
                            <td class="text-muted">Tipe peminjaman</td>
                            <th class="text-right">{{ $rent->format_tipe_peminjaman }}</th>
                        </tr>
                        @if ($rent->tipe_peminjaman != 1)
                        <tr>
                            <td class="text-muted">Driver</td>
                            <th class="text-right">{{ $rent->drivers->driver_name }}</th>
                        </tr>
                        @endif
                        @isset($rent->lokasi_penjemputan)
                        <tr>
                            <td class="text-muted">Lokasi penjemputan</td>
                            <th class="text-right">{{ $rent->lokasi_penjemputan }}</th>
                        </tr>
                        @endisset
                        <tr>
                            <td class="text-muted">Status</td>
                            <th class="text-right">
                                {{ $rent->status }}
                            </th>
                        </tr>
                    </tbody>
                </table>
                @if ($rent->status == 'jalan')
                <form class="mt-4" action="{{ route('rent_update', $rent->id) }}" method="post">
                    @csrf
                    <button class="btn btn-primary" type="submit">
                        <i class="fas fa-forward    "></i>
                        Kembalikan
                    </button>
                </form>
                @endif
            </div>
        </div>
    </div>
</div>
@endsection