routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->name('welcome');

Auth::routes(['verify' => true]);

Route::group(['prefix' => 'user', 'middleware' => 'auth'], function () {
    Route::get('home', 'HomeController@userHome')->name('user_home');

    Route::group(['prefix'  => 'rent'], function () {
        Route::get('/{id}', 'PeminjamanUserController@create_rent')->name('rentUser.create');
        Route::get('/', 'PeminjamanUserController@index')->name('rentUser.index');
        Route::get('/detail/{id}', 'PeminjamanUserController@show')->name('rentUser.show');
        Route::get('/{id}/bayar', 'PeminjamanUserController@bayar')->name('rentUser.bayar');
        Route::post('/', 'PeminjamanUserController@store_rent')->name('rentUser.store');
        Route::post('/{id}/bayar', 'PeminjamanUserController@konfirmasi')->name('rentUser.konfirmasi');
    });

    Route::resource('CustomerUser', 'CustomerUserController');
});

Route::group(['prefix' => 'admin', 'middleware' => 'is_admin'], function () {

    Route::get('dashboard', 'DashboardController@index')->name('adminDashboard');

    Route::get('rent/create', 'RentController@create_rent_admin')->name('create_rent_admin');
    Route::post('rent/create', 'RentController@store_rent_admin')->name('store_rent_admin');

    // Pending rent
    Route::get('rent/pending', 'RentController@index')->name('pending_index');
    Route::get('rent/pending/{id}', 'RentController@pending_show')->name('pending_show');
    Route::post('rent/pending', 'RentController@pending_update')->name('pending_update');
    Route::delete('rent/pending/{id}', 'RentController@pending_destroy')->name('pending_destroy');

    // on rent
    Route::get('rent/jalan', 'RentController@index')->name('rent_index');
    Route::get('rent/jalan/{id}', 'RentController@rent_show')->name('rent_show');
    Route::post('rent/jalan/{id}', 'RentController@rent_update')->name('rent_update');

    // Returned rent
    Route::get('rent/kembali', 'RentController@index')->name('return_index');
    Route::get('rent/kembali/{id}', 'RentController@rent_show')->name('return_info');

    // Checkout rent
    Route::get("rent/checkout/{id}", "RentController@checkout")->name("checkout_rent");

    // Car route
    Route::resource('car', 'CarController');

    // Driver route
    Route::resource('driver', 'DriverController');

    // Payment route
    Route::resource('payment', 'PaymentController');

    // Armada route
    Route::resource('armada', 'ArmadaController');

    // Customer route
    Route::resource('customer', 'CustomerController');

    // Read notifications
    Route::post('read/{id}', 'ReadNotificationController')->name('readNotification');
});

app/Car.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Car extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'jenis_mobil', 'nama_mobil', 'merk_mobil', 'bahan_bakar', 'harga'
    ];
    
    /**
     * 
     * RELATIONSHIP
     *
     */
    public function armadas() {
        return $this->hasMany('App\Armada', 'id_mobil', 'id');
    }
    
    /**
     * 
     * MUTATOR
     * 
     */
    public function getFormatHargaAttribute() {
        return "Rp.".$this->harga.",-";
    }

    public function getFormatJumlahArmadaAttribute() {
        $jumlah_armada = $this->armadas_count;
        $cek_jumlah_armada = ($jumlah_armada == 0 ? ' Kosong' : $jumlah_armada.' Unit');
        return $cek_jumlah_armada;
    }

    public function getNamaLengkapMobilAttribute() {
        return "{$this->merk_mobil} {$this->nama_mobil}";
    }
}

app/Rent.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Carbon\Carbon;

class Rent extends Model
{
    
    protected $fillable = [
        'id_customer', 'id_mobil', 'id_armada', 'tipe_peminjaman', 'id_driver', 'mulai_sewa', 'lama_sewa', 'habis_sewa', 'lokasi_penjemputan'
    ];
    
    /**
     * 
     * RELATIONSHIP
     *
     */
    public function customers() {
        return $this->hasOne('App\Customer', 'id', 'id_customer');
    }

    public function cars() {
        return $this->hasOne('App\Car', 'id', 'id_mobil');
    }

    public function drivers() {
        return $this->hasOne('App\Driver', 'id', 'id_driver');
    }

    public function armadas() {
        return $this->hasOne('App\Armada', 'id', 'id_armada');
    }

    
    /**
     * 
     * MUTATOR
     *
     */
    public function getFormatMulaiSewaAttribute() {
        return Carbon::parse($this->mulai_sewa)->format('j F Y');
    }

    public function getFormatLamaSewaAttribute() {
        return $this->lama_sewa." Hari";
    }

    public function getFormatHabisSewaAttribute() {
        return Carbon::parse($this->habis_sewa)->format('j F Y');
    }

    public function getFormatTipePeminjamanAttribute() {
        $text = ($this->tipe_peminjaman == 3 ? 'Mobil, Sopir dan Bahan bakar' : ($this->tipe_peminjaman == 2 ? 'Mobil dan Sopir' : 'Hanya mobil'));

        return $text;
    }

    public function getNamaLengkapMobilAttribute() {
        return "{$this->cars->merk_mobil} {$this->cars->nama_mobil}";
    }

    public function getLokasiGambarMobilAttribute() {
        return "images/{$this->cars->gambar}";
    }

    public function getLokasiGambarUserAttribute() {
        return "images/{$this->users->profile}";
    }

    public function getHargaMobilAttribute() {
        return $this->cars->harga * $this->lama_sewa;
    }

    public function getFormatHargaMobilAttribute() {
        return "Rp.".$this->harga_mobil.",-";
    }

    public function getHargaDriverAttribute() {
        if ($this->tipe_peminjaman == 2 || $this->tipe_peminjaman == 3) {
            $harga_driver = $this->lama_sewa * 100000;
            return $harga_driver;
        }

        return 0;
    }

    public function getFormatHargaDriverAttribute() {
        if ($this->harga_driver != 0) {
            return "Rp.{$this->harga_driver},-";
        }

        return "-";
    }

    public function getHargaBahanBakarAttribute() {
        if ($this->tipe_peminjaman == 3) {
            $harga_bahan_bakar = $this->lama_sewa * 100000;
            return $harga_bahan_bakar;
        }

        return 0;
    }

    public function getFormatHargaBahanBakarAttribute() {
        if ($this->harga_bahan_bakar != 0) {
            return "Rp.{$this->harga_bahan_bakar},-";
        }

        return "-";
    }

    public function getTotalHargaAttribute() {
        $harga = $this->harga_mobil + $this->harga_driver + $this->harga_bahan_bakar;
        return $harga;
    }

    public function getFormatTotalHargaAttribute() {
        return "Rp.".$this->total_harga.",-";
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'is_admin', 'phone_number', 'address'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function customers() {
        return $this->hasOne('App\Customer', 'id_user', 'id');
    }
}

resources/views/user/bayar.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row mt-5">
            <div class="col-lg-6 mt-4">
                <div class="card border-0 shadow-sm">
                    <div class="card-header border-0">
                        <div class="card-title">
                            <a href="{{ route('rentUser.index') }}"><i class="fa fa-arrow-left" aria-hidden="true"></i></a> Tagihan anda
                        </div>
                    </div>
                    <div class="card-body">
                        <table class="table table-borderless border">
                            <tr class="bg-secondary">
                                <td class="w-50">
                                    Nomor tagihan
                                </td>
                                <th class="text-right">
                                    {{ $payment->nomor_tagihan }}
                                </th>
                            </tr>
                            <tr>
                                <td class="w-50">Mobil</td>
                                <th class="text-right">
                                    {{ $payment->rents->format_harga_mobil }}
                                </th>
                            </tr>
                            @if ($payment->rents->tipe_peminjaman != 1)
                            <tr>
                                <td class="w-50">Sopir</td>
                                <th class="text-right">{{ $payment->rents->format_harga_driver }}</th>
                            <tr>
                            @endif
                            @if ($payment->rents->tipe_peminjaman == 3)
                            <tr>
                                <td class="w-50">Bahan bakar</td>
                                <th class="text-right">
                                    {{ $payment->rents->format_harga_bahan_bakar }}
                                </th>
                            </tr>
                            @endif
                            <tr>
                                <td colspan="1" class="border-top">
                                    Total
                                </td>
                                <th class="text-right border-top">
                                    {{ $payment->rents->format_total_harga }}
                                </th>
                            </tr>
                        </table>
                    </div>
                </div>
            </div>
            <div class="col-lg-6 mt-4">
                <div class="card border-0 shadow-sm">
                    <div class="card-header border-0">
                        <div class="card-title">
                            Konfirmasi pembayaran anda
                        </div>
                    </div>
                    <div class="card-body">
                        <form action="{{ route('rentUser.konfirmasi', $payment->id) }}" method="post" enctype="multipart/form-data">
                            @csrf
                            <div class="form-group">
                              <input type="file" class="form-control-file" name="bukti" id="bukti" placeholder="" aria-describedby="buktiHelp" required>
                              <small id="buktiHelp" class="form-text text-muted">Upload bukti pembayaran anda untuk konfirmasi</small>
                            </div>
                            <button type="submit" class="btn btn-primary">
                                Upload
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/user/createCustomer.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center mt-5">
        <div class="col-lg-6 mt-5">
            <div class="card">
                <div class="card-body">
                    <form action="{{ route('CustomerUser.store') }}" method="post">
                        @csrf
                        <div class="form-group">
                            <label for="nama">Nama lengkap</label>
                            <input type="text" name="nama" id="nama" class="form-control" placeholder="" aria-describedby="namaLengkap" required>
                        </div>
                        <div class="form-group">
                            <label for="nomor_ktp">Nomor ktp</label>
                            <input type="text" name="nomor_ktp" id="nomor_ktp" class="form-control" placeholder="" aria-describedby="nomorKtp" required>
                        </div>
                        <div class="form-group">
                            <label for="nomor_telepon">Nomor telepon</label>
                            <input type="text" name="nomor_telepon" id="nomor_telepon" class="form-control" placeholder="" aria-describedby="nomorTelepone">
                        </div>
                        <div class="form-group">
                            <label for="alamat">Alamat lengkap</label>
                            <textarea class="form-control" name="alamat" id="alamat" rows="3" required></textarea>
                        </div>
                        <button class="btn btn-primary" type="submit">Simpan</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/user/editCustomer.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center mt-5">
            <div class="col-lg-6 mt-5">
                <div class="card text-left">
                    <div class="card-body">
                        <form action="{{ route('CustomerUser.update', $customer->id) }}" method="post">
                            @csrf
                            @method('PUT')
                            <div class="form-group">
                                <label for="nama">Nama lengkap</label>
                                <input type="text" name="nama" value="{{ $customer->nama }}" id="nama" class="form-control" placeholder="" aria-describedby="nama">
                            </div>
                            <div class="form-group">
                                <label for="nomor_ktp">Nomor ktp</label>
                                <input type="text" name="nomor_ktp" value="{{ $customer->nomor_ktp }}" id="nomor_ktp" class="form-control" placeholder="" aria-describedby="nomor_ktp">
                            </div>
                            <div class="form-group">
                                <label for="nomor_telepon">Nomor telepon</label>
                                <input type="text" name="nomor_telepon" value="{{ $customer->nomor_telepon }}" id="nomor_telepon" class="form-control" placeholder="" aria-describedby="nomor_telepon">
                            </div>
                            <div class="form-group">
                                <label for="alamat">Alamat</label>
                                <textarea name="alamat" class="form-control" id="alamat">{{ $customer->alamat }}</textarea>
                            </div>
                            <div class="form-group">
                                <button class="btn btn-primary" type="submit">Simpan</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/user/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row mt-5">
        <div class="col mt-5">
            <div class="card border-0 shadow-sm">
                <div class="card-body">
                    <table class="table table-vertical-center">
                        <thead>
                            <tr>
                                <th>NO</th>
                                <th>Nama mobil</th>
                                <th>Tipe peminjaman</th>
                                <th>Status</th>
                                <th class="text-right">Aksi</th>
                            </tr>
                        </thead>
                        <tbody>
                            @forelse ($rents as $key => $rent)
                            <tr>
                                <td>
                                    {{ $key + 1 }}
                                </td>
                                <td>
                                    {{ $rent->nama_lengkap_mobil }}
                                </td>
                                <td>
                                    {{ $rent->format_tipe_peminjaman }}
                                </td>
                                <td>
                                    @if ($rent->status == 'pending')
                                    <div class="text-danger" role="alert">
                                        <i class="fas fa-hourglass-half    "></i> {{ $rent->status }}
                                    </div>
                                    @elseif($rent->status == 'jalan')
                                    <div class="text-success" role="alert">
                                        <i class="fa fa-list" aria-hidden="true"></i>
                                        dikonfirmasi
                                    </div>
                                    @else
                                    <div class="text-primary" role="alert">
                                        <i class="fas fa-check    "></i> selesai
                                    </div>
                                    @endif
                                </td>
                                <td class="text-right">
                                <a href="{{ route('rentUser.show', $rent->id) }}" class="btn btn-success btn-sm">
                                        <i class="fas fa-eye    "></i> Detail
                                    </a>
                                    @if ($rent->status == 'pending')
                                    <a href="{{ route('rentUser.bayar', $rent->id) }}" class="btn btn-primary btn-sm">
                                        <i class="fas fa-money-bill    "></i> Bayar
                                    </a>
                                    @endif
                                </td>
                            </tr>
                            @empty
                            <tr>
                                <td class="text-center" colspan="5">
                                    Data not found
                                </td>
                            </tr>
                            @endforelse
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/user/indexCustomer.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center mt-5">
            <div class="col-lg-6 mt-5">
                <div class="card">
                    <div class="card-header d-flex flex-wrap border-0">
                        <div class="card-title align-self-center">
                            Data diri
                        </div>
                        @if (empty($customer))
                        <a href="{{ route("CustomerUser.create") }}" class="btn btn-primary btn-sm ml-auto">
                            <i class="fas fa-plus    "></i>
                        </a>
                        @endif
                    </div>
                    <div class="card-body">
                        @if (!empty($customer))
                        <table class="table table-borderless mb-5">
                            <tr>
                                <td>Nama</td>
                                <th class="text-right">
                                    {{ $customer->nama }}
                                </th>
                            </tr>
                            <tr>
                                <td>Nomor ktp</td>
                                <th class="text-right">
                                    {{ $customer->nomor_ktp }}
                                </th>
                            </tr>
                            <tr>
                                <td>Nomor telepon</td>
                                <th class="text-right">
                                    {{ $customer->nomor_telepon }}
                                </th>
                            </tr>
                            <tr>
                                <td>Alamat</td>
                                <th class="text-right">
                                    {{ $customer->alamat }}
                                </th>
                            </tr>
                        </table>
                        <a href="{{ route('CustomerUser.edit', $customer->id) }}" class="btn btn-primary">
                            Edit
                        </a>
                        @else
                        <div class="text-center text-danger">
                            Data not found
                        </div>
                        @endif
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/user/rent.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row align-items-stretch mt-5">
        <div class="col-lg-4 mt-4">
            <div class="card border-0 shadow-sm">
                <div class="card-header border-0">
                    <div class="card-title">Informasi mobil</div>
                </div>
                <div class="card-body">
                    <img class="img-fluid mb-3" src="{{ asset('storage/images/'.$cars->gambar) }}" alt="gambar_mobil">
                    <table class="table table-borderless">
                        <tr>
                            <td class="text-muted w-50">Jenis mobil</td>
                            <th class="text-right">{{ $cars->jenis_mobil }}</th>
                        </tr>
                        <tr>
                            <td class="text-muted w-50">Nama mobil</td>
                            <th class="text-right">{{ $cars->nama_mobil }}</th>
                        </tr>
                        <tr>
                            <td class="text-muted w-50">Merk mobil</td>
                            <th class="text-right">{{ $cars->merk_mobil }}</th>
                        </tr>
                        <tr>
                            <td class="text-muted w-50">Bahan bakar</td>
                            <th class="text-right">{{ $cars->bahan_bakar }}</th>
                        </tr>
                        <tr>
                            <td class="text-muted w-50">Harga</td>
                            <th class="text-right">{{ $cars->format_harga }} / hari</th>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-8 mt-4">
            <div class="card border-0 shadow-sm">
                <div class="card-header border-0">
                    <div class="card-title">Pemesanan</div>
                </div>
                <div class="card-body">
                    <form action="{{ route('rentUser.store') }}" method="post" id="store_rent">
                        @csrf
                        <input type="hidden" name="id_mobil" value="{{ $cars->id }}">
                        <input type="hidden" name="id_customer" value="{{ empty($user->customers) ? "" : $user->customers->id }}">
                        <div class="form-group">
                            <label for="id_customer">Data diri</label>
                            <input type="text" class="form-control" id="id_customer" disabled value="{{ empty($user->customers) ? '' : $user->customers->nama }}">
                            @empty($user->customers)
                            <small id="helpId" class="form-text text-danger">
                                Anda belum melengkapi data diri anda silahkan lengkapi data anda terlebih dahulu
                                <a href="{{ route('CustomerUser.create') }}"> disini!</a>
                            </small>
                            @endempty
                        </div>
                        <div class="form-group">
                            <label for="tipe_peminjaman">Tipe peminjaman</label>
                            <select class="form-control pointer" name="tipe_peminjaman" id="tipe_peminjaman" required>
                                <option disabled {{ (old('tipe_peminjaman') ? '' : 'selected')}}></option>
                                <option value="1" {{ (old('tipe_peminjaman') == '1' ? 'selected' : '')}}>Hanya mobil</option>
                                <option value="2" {{ (old('tipe_peminjaman') == '2' ? 'selected' : '')}}>Mobil dan sopir</option>
                                <option value="3" {{ (old('tipe_peminjaman') == '3' ? 'selected' : '')}}>Mobil, sopir dan bahan bakar</option>
                            </select>
                        </div>
                        <div class="form-group">
                            <label for="">Mulai sewa</label>
                            <input type="date" id="mulai_sewa" name="mulai_sewa" value="{{ old('mulai_sewa') }}" class="form-control pointer" min="2020-04-21" required>
                        </div>
                        <div class="form-group">
                            <label for="lama_sewa">Lama sewa</label>
                            <div class="input-group">
                                <input type="number" min="1" class="form-control" name="lama_sewa" id="lama_sewa" value="{{ old('lama_sewa') }}" autocomplete="off" required>
                                <div class="input-group-append">
                                    <label class="input-group-text">Hari</label>
                                </div>
                            </div>
                        </div>
                        <div class="form-group" id="lokasi_penjemputan">
                            <label for="lokasi_penjemputan">Lokasi penjemputan</label>
                            <textarea name="lokasi_penjemputan" class="form-control">{{ old('lokasi_penjemputan') }}</textarea>
                            <small id="helpId" class="text-muted">Lokasi penjemputan jika anda menyewa sopir</small>
                        </div>
                        <div class="form-group">
                            <label for="harga">Estimasi harga</label>
                            <div class="input-group">
                                <input name="harga" id="harga" class="form-control" value="{{ session()->get('harga') }}" disabled>
                                <div class="input-group-append">
                                    <button class="btn btn-primary" name="cek" type="submit" value="0" id="cek_estimasi">
                                        Cek harga
                                    </button>
                                </div>
                            </div>
                        </div>
                        <button name="create" value="1" type="submit" class="btn btn-primary mt-3">
                            <i class="fa fa-shopping-cart text-white" aria-hidden="true"></i>
                            Pesan
                        </button>
                    </form>
                </div>
            </div>
        </div>
        
    </div>
</div>
@endsection

resources/views/user/rentDetail.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center mt-5">
            <div class="col-lg-6 mt-4">
                <div class="card">
                    <div class="card-header border-0">
                        <div class="card-title">
                            <a href="{{ url()->previous() }}">
                                <i class="fas fa-arrow-left    "></i>
                            </a>
                            Detail peminjaman
                        </div>
                    </div>
                    <div class="card-body">
                        <img src="{{ asset('storage/images/'.$rent->cars->gambar) }}" class="img-fluid" alt="">
                        <table class="table table-borderless">
                            <tbody>
                                <tr>
                                    <td class="text-muted w-50">Nama penyewa</td>
                                    <th class="text-right">{{ $rent->customers->nama }}</th>
                                </tr>
                                <tr>
                                    <td class="text-muted w-50">Nama mobil</td>
                                    <th class="text-right">{{ $rent->nama_lengkap_mobil }}</th>
                                </tr>
                                <tr>
                                    <td class="text-muted">Mulai sewa</td>
                                    <th class="text-right">{{ $rent->format_mulai_sewa }}</th>
                                </tr>
                                <tr>
                                    <td class="text-muted">Lama sewa</td>
                                    <th class="text-right">{{ $rent->format_lama_sewa }}</th>
                                </tr>
                                <tr>
                                    <td class="text-muted">Habis sewa</td>
                                    <th class="text-right">{{ $rent->format_habis_sewa }}</th>
                                </tr>
                                <tr>
                                    <td class="text-muted">Tipe peminjaman</td>
                                    <th class="text-right">{{ $rent->format_tipe_peminjaman }}</th>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection