routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->name('welcome');

Auth::routes(['verify' => true]);

Route::group(['prefix' => 'user', 'middleware' => 'auth'], function () {
    Route::get('home', 'HomeController@userHome')->name('user_home');

    Route::group(['prefix'  => 'rent'], function () {
        Route::get('/{id}', 'PeminjamanUserController@create_rent')->name('rentUser.create');
        Route::get('/', 'PeminjamanUserController@index')->name('rentUser.index');
        Route::get('/detail/{id}', 'PeminjamanUserController@show')->name('rentUser.show');
        Route::get('/{id}/bayar', 'PeminjamanUserController@bayar')->name('rentUser.bayar');
        Route::post('/', 'PeminjamanUserController@store_rent')->name('rentUser.store');
        Route::post('/{id}/bayar', 'PeminjamanUserController@konfirmasi')->name('rentUser.konfirmasi');
    });

    Route::resource('CustomerUser', 'CustomerUserController');
});

Route::group(['prefix' => 'admin', 'middleware' => 'is_admin'], function () {

    Route::get('dashboard', 'DashboardController@index')->name('adminDashboard');

    Route::get('rent/create', 'RentController@create_rent_admin')->name('create_rent_admin');
    Route::post('rent/create', 'RentController@store_rent_admin')->name('store_rent_admin');

    // Pending rent
    Route::get('rent/pending', 'RentController@index')->name('pending_index');
    Route::get('rent/pending/{id}', 'RentController@pending_show')->name('pending_show');
    Route::post('rent/pending', 'RentController@pending_update')->name('pending_update');
    Route::delete('rent/pending/{id}', 'RentController@pending_destroy')->name('pending_destroy');

    // on rent
    Route::get('rent/jalan', 'RentController@index')->name('rent_index');
    Route::get('rent/jalan/{id}', 'RentController@rent_show')->name('rent_show');
    Route::post('rent/jalan/{id}', 'RentController@rent_update')->name('rent_update');

    // Returned rent
    Route::get('rent/kembali', 'RentController@index')->name('return_index');
    Route::get('rent/kembali/{id}', 'RentController@rent_show')->name('return_info');

    // Checkout rent
    Route::get("rent/checkout/{id}", "RentController@checkout")->name("checkout_rent");

    // Car route
    Route::resource('car', 'CarController');

    // Driver route
    Route::resource('driver', 'DriverController');

    // Payment route
    Route::resource('payment', 'PaymentController');

    // Armada route
    Route::resource('armada', 'ArmadaController');

    // Customer route
    Route::resource('customer', 'CustomerController');

    // Read notifications
    Route::post('read/{id}', 'ReadNotificationController')->name('readNotification');
});

app/Car.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Car extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'jenis_mobil', 'nama_mobil', 'merk_mobil', 'bahan_bakar', 'harga'
    ];
    
    /**
     * 
     * RELATIONSHIP
     *
     */
    public function armadas() {
        return $this->hasMany('App\Armada', 'id_mobil', 'id');
    }
    
    /**
     * 
     * MUTATOR
     * 
     */
    public function getFormatHargaAttribute() {
        return "Rp.".$this->harga.",-";
    }

    public function getFormatJumlahArmadaAttribute() {
        $jumlah_armada = $this->armadas_count;
        $cek_jumlah_armada = ($jumlah_armada == 0 ? ' Kosong' : $jumlah_armada.' Unit');
        return $cek_jumlah_armada;
    }

    public function getNamaLengkapMobilAttribute() {
        return "{$this->merk_mobil} {$this->nama_mobil}";
    }
}

app/Http/Controllers/CarController.php
<?php

namespace App\Http\Controllers;

use Alert;
use App\Car;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Storage;

class CarController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        // set default order value
        $orderBy = $request->orderBy ? $request->orderBy : 'created_at';
        $orderType = $request->orderType ? $request->orderType : 'DESC';

        if ($request->has('search_query')) {
            $cars = Car::withCount('armadas')
            ->where('jenis_mobil', 'LIKE', '%'.$request->search_query.'%')
            ->orWhere('nama_mobil', 'LIKE', '%'.$request->search_query.'%')
            ->orWhere(\DB::raw('CONCAT(merk_mobil," ",nama_mobil)'), 'LIKE', '%'.$request->search_query.'%')
            ->orWhere('merk_mobil', 'LIKE', '%'.$request->search_query.'%')
            ->orWhere('harga', 'LIKE', '%'.$request->search_query.'%')
            ->orderBy($orderBy, $orderType)
            ->paginate(10);
        } else {
            $cars = Car::withCount('armadas')
            ->orderBy($orderBy, $orderType)
            ->paginate(10);
        }

        // append order query
        if ($orderBy != 'created_at') {
            $cars->appends([
                'orderBy'   => $orderBy,
                'orderType' => $orderType
            ]);
        }

        return view('car.index')->with([
            'cars' => $cars,
            'orderType' => $orderType == 'DESC' ? 'ASC' : 'DESC'
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('car/create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        if ($request->hasFile("gambar")) {
            $image_name = time().'.'.$file->getClientOriginalExtension();
            Storage::putFileAs("public/images", $request->file('gambar'), $image_name);
        } else {
            $image_name = 'default.jpg';
        }

        $car = new Car;
        $car->jenis_mobil = $request->jenis_mobil;
        $car->nama_mobil = $request->nama_mobil;
        $car->merk_mobil = $request->merk_mobil;
        $car->bahan_bakar = $request->bahan_bakar;
        $car->harga = $request->harga;
        $car->gambar = $image_name;
        $car->save();

        Alert::success('Berhasil', 'Data telah ditambahkan!');
        return redirect()->route("car.index");
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Car  $car
     * @return \Illuminate\Http\Response
     */
    public function show(Car $car)
    {
        $car = Car::find($car->id);
        return view('car/show')->with('car', $car);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Car  $car
     * @return \Illuminate\Http\Response
     */
    public function edit(Car $car)
    {
        $car = Car::find($car->id);
        return view('car/edit')->with('car', $car);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Car  $car
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Car $car)
    {
        $car = Car::find($car->id);
        $file = $request->file('gambar');
        
        if ($request->hasFile("gambar")) {
            $image_name = time().'.'.$file->getClientOriginalExtension();
            Storage::putFileAs("public/images", $file, $image_name);
        } else {
            $image_name = $car->gambar;
        }

        $car->jenis_mobil = $request->jenis_mobil;
        $car->nama_mobil = $request->nama_mobil;
        $car->merk_mobil = $request->merk_mobil;
        $car->bahan_bakar = $request->bahan_bakar;
        $car->harga = $request->harga;
        $car->gambar = $image_name;
        $car->save();

        Alert::success('Berhasil', 'Data telah diubah!');
        return redirect()->route("car.index");
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Car  $car
     * @return \Illuminate\Http\Response
     */
    public function destroy(Car $car)
    {
        Car::find($car->id)->delete();
        Alert::success('Berhasil', 'Data telah dihapus!');
        return redirect()->back();
    }
}

resources/views/car/create.blade.php
<!-- Modal -->
<div class="modal fade" id="mobil" tabindex="-1" role="dialog" aria-labelledby="mobil" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header border-bottom-0">
                <h5 class="modal-title">Tambah mobil</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form action="{{ route('car.store') }}" method="post" enctype="multipart/form-data">
                    @csrf
                    <div class="form-row">
                        <div class="form-group col-lg-4">
                            <label for="">Tipe mobil</label>
                            <input type="text" class="form-control" name="jenis_mobil" id="" aria-describedby="helpId" placeholder="" required>
                            <small class="text-muted">
                                Contoh: MPV, Sedan dll.
                            </small>
                        </div>
                        <div class="form-group col-lg-4">
                            <label for="">Merk mobil</label>
                            <input type="text" class="form-control" name="merk_mobil" id="" aria-describedby="helpId" placeholder="" required>
                        </div>
                        <div class="form-group col-lg-4">
                            <label for="">Nama mobil</label>
                            <input type="text" class="form-control" name="nama_mobil" id="" aria-describedby="helpId" placeholder="" required>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="">Bahan bakar</label>
                        <input type="text" class="form-control" name="bahan_bakar" id="" aria-describedby="helpId" placeholder="" required>
                    </div>
                    <div class="form-group">
                        <label for="">Harga sewa</label>
                        <input type="number" class="form-control" name="harga" id="" aria-describedby="helpId" placeholder="" required>
                    </div>
                    <div class="form-group">
                        <label for="gambar">Gambar mobil</label>
                        <input type="file" name="gambar" class="form-control-file" id="gambar">
                    </div>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            </div>
        </div>
    </div>
</div>

resources/views/car/edit.blade.php
@extends('adminlte::page')

@section('content')
<div class="row">
    <div class="col-lg-6">
        <div class="card">
            <div class="card-header border-0">
                <div class="card-title">
                    Update informasi mobil
                </div>
            </div>
            <div class="card-body"> 
            <form action="{{ route('car.update', $car->id) }}" method="post" enctype="multipart/form-data">
                @csrf
                @method('PATCH')
                <div class="form-group">
                <label for="">Jenis mobil</label>
                <input type="text" class="form-control" name="jenis_mobil" value="{{ $car->jenis_mobil }}" placeholder="">
                </div>
                <div class="form-group">
                    <label for="">Nama mobil</label>
                    <input type="text" class="form-control" name="nama_mobil" value="{{ $car->nama_mobil }}" placeholder="">
                </div>
                <div class="form-group">
                    <label for="">Merk mobil</label>
                    <input type="text" class="form-control" name="merk_mobil" value="{{ $car->merk_mobil }}" placeholder="">
                </div>
                <div class="form-group">
                    <label for="">Bahan bakar</label>
                    <input type="text" class="form-control" name="bahan_bakar" value="{{ $car->bahan_bakar }}" placeholder="">
                </div>
                <div class="form-group">
                    <label for="">Harga sewa</label>
                    <input type="text" class="form-control" name="harga" value="{{ $car->harga }}" placeholder="">
                </div>
                <div class="form-group">
                    <label for="">Gambar</label>
                    <input type="file" class="form-control-file" name="gambar" value="{{ $car->gambar }}" placeholder="" >
                </div>
                <button type="submit" class="btn btn-primary">
                    <i class="fas fa-upload    "></i> Update
                </button>
                <a href="{{ route('car.index') }}" type="button" class="btn btn-secondary">
                    <i class="fas fa-arrow-left    "></i>
                    Cancel
                </a>
            </form>
            </div>
        </div>
    </div>
</div>
@stop

resources/views/car/index.blade.php
@extends('adminlte::page')

@section('content')
<div class="card">
    <div class="card-header d-flex flex-wrap align-items-center border-bottom-0">
        <h4 class="card-title text-bold">Data mobil</h4> 
        <form method="GET" action="{{ route('car.index') }}" class="input-group ml-auto mr-2" style="width: 250px">
            <input type="text" class="form-control bg-light" name="search_query" placeholder="search" required>
            <div class="input-group-append">
                <button class="btn btn-light px-3 border"><span class="fa fa-search"></span></button>
            </div>
        </form>
        <!-- Button trigger modal -->
        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#mobil">
            <span class="fa fa-plus"></span>
        </button>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-vertical-center">
                <thead>
                    <tr>
                        <th>
                            NO
                        </th>
                        <th>
                            <a href="{{ Request::fullUrlWithQuery([
                                'orderBy'   => 'jenis_mobil',
                                'orderType' => $orderType
                            ]) }}" class="btn btn-link text-dark font-weight-bold p-0">
                                JENIS MOBIL
                                <i class="fas fa-sort"></i>
                            </a>
                        </th>
                        <th>
                            <a href="{{ Request::fullUrlWithQuery([
                                'orderBy'   => 'merk_mobil',
                                'orderType' => $orderType
                            ]) }}" class="btn btn-link text-dark font-weight-bold p-0">
                                MERK MOBIL
                                <i class="fas fa-sort"></i>
                            </a>
                        </th>
                        <th>
                            <a href="{{ Request::fullUrlWithQuery([
                                'orderBy'   => 'nama_mobil',
                                'orderType' => $orderType
                            ]) }}" class="btn btn-link text-dark font-weight-bold p-0">
                                NAMA MOBIL
                                <i class="fas fa-sort"></i>
                            </a>
                        </th>
                        <th>
                            <a href="{{ Request::fullUrlWithQuery([
                                'orderBy'   => 'harga',
                                'orderType' => $orderType
                            ]) }}" class="btn btn-link text-dark font-weight-bold p-0">
                                HARGA
                                <i class="fas fa-sort"></i>
                            </a>
                        </th>
                        <th>
                            <a href="{{ Request::fullUrlWithQuery([
                                'orderBy'   => 'armadas_count',
                                'orderType' => $orderType
                            ]) }}" class="btn btn-link text-dark font-weight-bold p-0">
                                ARMADA
                                <i class="fas fa-sort"></i>
                            </a>
                        </th>
                        <th style="width: 180px" class="text-right">Aksi</th>
                    </tr>
                </thead>
                <tbody>
                @foreach ($cars as $key => $car)
                    <tr>
                        <td>
                            {{ $key + 1 }}
                        </td>
                        <td scope="row">{{ $car->jenis_mobil }}</td>
                        <td>{{ $car->merk_mobil }}</td>
                        <td>{{ $car->nama_mobil }}</td>
                        <td>{{ $car->format_harga }}</td>
                        <td>{{ $car->format_jumlah_armada }}</td>
                        <td class="text-right">
                            <a href="{{ route('car.show', $car->id) }}" class="btn btn-success btn-sm"><span class="fa fa-eye"></span></a>
                            <a href="{{ route('car.edit', $car->id) }}" type="button" class="btn btn-primary btn-sm"><span class="fa fa-pen"></span></a>
                            <button type="button" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#modalDelete">
                                <i class="fas fa-trash    "></i>
                            </button>
                            @include('car.modalDelete')
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>
@include('car.create')
@endsection

resources/views/car/modalDelete.blade.php
<!-- Modal -->
<div class="modal fade" id="modalDelete" tabindex="-1" role="dialog" aria-labelledby="modalDelete" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header border-0">
                <h5 class="modal-title">Konfirmasi</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
            </div>
            <div class="modal-body text-left">
                Apa anda yakin ingin menghapus data ini?
            </div>
            <div class="modal-footer border-0">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Tidak</button>
                <form action="{{ route('car.destroy', $car->id) }}" method="post" class="d-inline">
                    @csrf
                    @method("DELETE")
                    <button type="submit" class="btn btn-primary">
                        Ya, Hapus!
                    </button>
                </form>
            </div>
        </div>
    </div>
</div>

resources/views/car/show.blade.php
@extends('adminlte::page')

@section('content')
<div class="card">
    <div class="card-header border-bottom-0">
        <div class="card-title">
            <a href="{{ url()->previous() }}" class="mr-3">
                <span class="fa fa-arrow-left text-primary"></span>
            </a>
            Informasi detail mobil
        </div>
    </div>
    <div class="card-body">
        <div class="row align-items-center">
            <div class="col-lg-6 text-center">
                <img src="{{ asset('storage/images/'.$car->gambar) }}" alt="silakan tambah gambar mobil di menu edit" style="max-height: 400px; object-fit: cover">
            </div>
            <div class="col-lg-6">
                <div class="d-flex justify-content-center">
                    <table class="table w-75">
                        <tr>
                            <td class="text-muted border-top-0">Jenis mobil</td>
                            <th class="text-right border-top-0">{{ $car->jenis_mobil }}</th>
                        </tr>
                        <tr>
                            <td class="text-muted">Merk mobil</td>
                            <th class="text-right">{{ $car->merk_mobil }}</th>
                        </tr>
                        <tr>
                            <td class="text-muted">Nama mobil</td>
                            <th class="text-right">{{ $car->nama_mobil }}</th>
                        </tr>
                        <tr>
                            <td class="text-muted">Bahan bakar</td>
                            <th class="text-right">{{ $car->bahan_bakar }}</th>
                        </tr>
                        <tr>
                            <td class="text-muted">Harga mobil</td>
                            <th class="text-right">{{ $car->format_harga }}</th>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection